modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/yanny7/advancedlootinfo/issues" #optional

[[mods]] #mandatory
modId = "ali" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile="logo.png" #optional
logoBlur = false
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)

[[mixins]]
config = "ali.mixins.json"
[[mixins]]
config = "ali.neoforge.mixins.json"

[[dependencies.ali]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neoforge_loader_version_range}" #mandatory
ordering = "AFTER" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.ali]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ali]]
modId="emi"
mandatory=false
versionRange="${emi_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.ali]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.ali]]
modId="rei"
mandatory=false
versionRange="${rei_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.ali]]
modId="lootjs"
mandatory=false
ordering="AFTER"
side="BOTH"
